Bug Fix: Mutliple filter components overwrite each others conditions when filtering the same grid
xdev-software/vaadin-simple-grid-filter pull request #7
Opened 2024-10-18 11:04 UTC by lcarrasco-xdev

**Steps to reproduce:**

1. Add two filter components which should filter the same grid to the ui.
2. Add a custom condition to the first filter component.
3. Add a custom condition to the second filter component.
4. The second condition overwrites the first one.

**Expected behavior:** At step 4 the second condition should not overwrite the first one. The second condition should be combined with the first condition.

2024-10-21 07:11 UTC, AB-xdev requested changes
Some general problems from my side:
1. I'm having some serious doubts if this change is needed in the first place. I think the use-case of needing multiple "filter components" for one Grid is extremely unlikely.
2. The current solution is not bound to the Grid that should be filter but instead to the UI, meaning that all "filter components" on the same UI are updated, which can result in unexpected behavior.
3. Self-registering an listener for communication between different components is not a good practice and breaks encapsulation. This will result in "works with magic"-behavior observed by users of the component.

2024-10-21 07:11 UTC, AB-xdev commented on vaadin-simple-grid-filter/src/main/java/software/xdev/vaadin/FilterComponent.java
> +	private static class FilterComponentResetGridFilterEvent extends ComponentEvent<FilterComponent>
Type is missing, see sonar for more details

2024-10-21 07:11 UTC, AB-xdev commented on vaadin-simple-grid-filter/src/main/java/software/xdev/vaadin/FilterComponent.java
> +	private void updateGridFilter()
Method is called ``updateGridFilter`` but it just removes filters and throws a ``FilterComponentResetGridFilterEvent``.

Should likely be called ``resetGridFilters`` or?

2024-10-21 07:11 UTC, AB-xdev commented on vaadin-simple-grid-filter/src/main/java/software/xdev/vaadin/FilterComponent.java
> +		return predicates.stream().map(p -> p.test(item)).reduce(Boolean::logicalAnd).orElseThrow();
Can likely be written with Streaming API

2024-10-21 07:11 UTC, AB-xdev commented on vaadin-simple-grid-filter/src/main/java/software/xdev/vaadin/FilterComponent.java
> +	private Registration registration;
Should be protected so that it can be overriden

2024-11-12 07:42 UTC, closed without merging

2024-11-12 07:42 UTC, JohannesRabauer commented
I think @AB-xdev has good points as to why we should not merge this change: https://github.com/xdev-software/vaadin-simple-grid-filter/pull/7#pullrequestreview-2381106280
That's why i'm closing this PR for now.